# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dir2mcp < Formula
  desc "Deploy any local directory as an MCP knowledge server with indexing, retrieval, and citations."
  homepage "https://github.com/dirstral/dir2mcp"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirstral/dir2mcp/releases/download/v0.9.2/dir2mcp_0.9.2_darwin_amd64.tar.gz"
      sha256 "769d8516e25a1f4a1cb5b292184aa02ac71faa83f30f8794acc3c187a3b91360"

      define_method(:install) do
        bin.install "dir2mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirstral/dir2mcp/releases/download/v0.9.2/dir2mcp_0.9.2_darwin_arm64.tar.gz"
      sha256 "7c5fc8bdd92605b9e65b01ee06e2568071bac50fc1cb5235368abf2425abe7fa"

      define_method(:install) do
        bin.install "dir2mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirstral/dir2mcp/releases/download/v0.9.2/dir2mcp_0.9.2_linux_amd64.tar.gz"
      sha256 "cd188248362e46c18db724421c3ee0d79634ac8a2cae65e441586d7762289dff"
      define_method(:install) do
        bin.install "dir2mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirstral/dir2mcp/releases/download/v0.9.2/dir2mcp_0.9.2_linux_arm64.tar.gz"
      sha256 "07eddcdcd5d5a28058a87327d736d607f30f9dac684e543d3f92bcb3569a62db"
      define_method(:install) do
        bin.install "dir2mcp"
      end
    end
  end

  conflicts_with "dir2mcp-full"

  def caveats
    <<~EOS
      If `dir2mcp version` reports an older version after upgrading,
      run `hash -r` (bash/zsh) in any open shells to refresh the
      command cache, or open a new terminal.
    EOS
  end

  test do
    system "#{bin}/dir2mcp", "version"
  end
end
