# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dir2mcp < Formula
  desc "Deploy any local directory as an MCP knowledge server with indexing, retrieval, and citations."
  homepage "https://github.com/dirstral/dir2mcp"
  version "0.11.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dirstral/dir2mcp/releases/download/v0.11.4/dir2mcp_0.11.4_darwin_amd64.tar.gz"
      sha256 "b1fe04532c641d8634241f8042a1924cd81fb5d043e23f987d1947d781ceda09"

      define_method(:install) do
        bin.install "dir2mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dirstral/dir2mcp/releases/download/v0.11.4/dir2mcp_0.11.4_darwin_arm64.tar.gz"
      sha256 "fb544cef91b8b499c54c15340efc45b2a41dc98789629ae2f4540ba4c7c13fa3"

      define_method(:install) do
        bin.install "dir2mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirstral/dir2mcp/releases/download/v0.11.4/dir2mcp_0.11.4_linux_amd64.tar.gz"
      sha256 "16379dabde3c92cbb7d278dae57bf69d49cd953b1b37fba64f6df5a0f6377663"
      define_method(:install) do
        bin.install "dir2mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dirstral/dir2mcp/releases/download/v0.11.4/dir2mcp_0.11.4_linux_arm64.tar.gz"
      sha256 "56956815b33a6d92b703c3569c5a9e2513e2159d4ac4f25151cdf25483399ad9"
      define_method(:install) do
        bin.install "dir2mcp"
      end
    end
  end

  conflicts_with "dir2mcp-full"

  def caveats
    <<~EOS
      If `dir2mcp version` reports an older version after upgrading,
      run `hash -r` (bash/zsh) in any open shells to refresh the
      command cache, or open a new terminal.
    EOS
  end

  test do
    system "#{bin}/dir2mcp", "version"
  end
end
