# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dirstral < Formula
  desc "Interactive TUI client for dir2mcp knowledge bases."
  homepage "https://github.com/Dirstral/dir2mcp"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dirstral/dir2mcp/releases/download/v0.3.0/dirstral_0.3.0_darwin_amd64.tar.gz"
      sha256 "0668ad638a1483b2b6cc05884cd88f6ddee3c02efee157f559feddc329c7e8a9"

      define_method(:install) do
        bin.install "dirstral"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dirstral/dir2mcp/releases/download/v0.3.0/dirstral_0.3.0_darwin_arm64.tar.gz"
      sha256 "b377bc9beb206bcae5076297b673f6bf9029957355c2e273098a68beffd8ab63"

      define_method(:install) do
        bin.install "dirstral"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dirstral/dir2mcp/releases/download/v0.3.0/dirstral_0.3.0_linux_amd64.tar.gz"
      sha256 "52ad42c96bec56cd0e716cb1cc4c46d7a2cf51826e7ed483f27a45a47992400b"
      define_method(:install) do
        bin.install "dirstral"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dirstral/dir2mcp/releases/download/v0.3.0/dirstral_0.3.0_linux_arm64.tar.gz"
      sha256 "d90db2c014a961ecf19137b3c475e5a3a48d5afad1e2396bb658baf92a6d4523"
      define_method(:install) do
        bin.install "dirstral"
      end
    end
  end

  test do
    system "#{bin}/dirstral", "version"
  end
end
